/*
eff Throw[a: Type] {
    def throw[a: Type](x: a): Unit
}

def g(): Unit \ fooeffects =
    foo()

def foo(f: a -> b \ ef): Unit \ Throw[Int32] + Throw[a -> b \ ef] + Throw[fs signature => foos signature => ???] =
    Throw.throw(5);
    Throw.throw(f);
    Throw.throw(g);
    ()


def main(): Unit =
    run {
        foo(x -> x + 1)
    }
    with handler Throw[Int32]
    with handler Throw[a -> b \ ef]
    with handler Throw[Unit -> asdasd] {
        def throw(x, k) = ???
    }

*/


